import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, test } from "node:test";

import { checkTestPolicy } from "./check-test-policy.mjs";

const temporaryDirectories = [];

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    fs.rmSync(directory, { recursive: true, force: true });
  }
});

const CORE_BLOCK = [
  "<!-- test-policy:core:start -->",
  "1. rule one",
  "2. rule two",
  "<!-- test-policy:core:end -->",
].join("\n");

const POLICY_MARKDOWN = `# Testing policy\n\n${CORE_BLOCK}\n`;

function validScenario(id, category) {
  return {
    schemaVersion: 1,
    id,
    category,
    title: "Example",
    context: "context",
    request: "request",
    expected: { action: "add", rationale: "because" },
  };
}

function writeEvalCorpus(rootDir) {
  const dir = path.join(rootDir, "verification/test-policy-evals");
  fs.mkdirSync(dir, { recursive: true });
  const scenarios = [
    ["control-a.json", validScenario("control-a", "control")],
    ["known-failure-a.json", validScenario("known-failure-a", "known-failure")],
    ["boundary-a.json", validScenario("boundary-a", "boundary")],
  ];
  for (const [fileName, scenario] of scenarios) {
    fs.writeFileSync(path.join(dir, fileName), JSON.stringify(scenario));
  }
  fs.writeFileSync(
    path.join(dir, "index.json"),
    JSON.stringify({ schemaVersion: 1, scenarios: scenarios.map(([f]) => f) }),
  );
}

function writeFile(rootDir, relativePath, contents) {
  const filePath = path.join(rootDir, relativePath);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents);
}

/** Builds a minimal repository fixture that passes every check, then lets
 * each test corrupt exactly one part of it. */
function createValidFixture() {
  const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), "town-check-test-policy-"));
  temporaryDirectories.push(rootDir);

  writeEvalCorpus(rootDir);
  writeFile(rootDir, "docs/agents/testing-policy.md", POLICY_MARKDOWN);

  const generatedBlock = generatedAdapterBlockFixture();
  writeFile(rootDir, "AGENTS.md", `# AGENTS.md\n\n${generatedBlock}\n`);
  writeFile(rootDir, "CLAUDE.md", `# Working in this repo\n\n${generatedBlock}\n`);

  writeFile(
    rootDir,
    "packages/example/src/foo.test.ts",
    `test("does the thing", () => {});\n`,
  );

  const claims = {
    schemaVersion: 1,
    claims: [
      {
        id: "V-EXAMPLE",
        requirement: "the thing happens",
        primary: {
          file: "packages/example/src/foo.test.ts",
          test: "does the thing",
          boundary: "pure function",
        },
        cases: ["happy-path"],
        setup: "none",
        source: "test",
      },
    ],
  };
  writeFile(rootDir, "verification/test-claims.json", JSON.stringify(claims, null, 2));
  writeFile(
    rootDir,
    "verification/legacy-test-baseline.json",
    JSON.stringify(
      {
        schemaVersion: 1,
        generatedBy: "node scripts/generate-legacy-baseline.mjs --write",
        declarationCount: 0,
        declarations: [],
      },
      null,
      2,
    ) + "\n",
  );

  return rootDir;
}

/** Same shape scripts/sync-agent-test-policy.mjs's buildGeneratedBlock
 * produces, duplicated here only as fixture data so the fixture doesn't
 * depend on importing production code to construct its own expectation. */
function generatedAdapterBlockFixture() {
  const coreText = "1. rule one\n2. rule two";
  const checksum = createHash("sha256")
    .update(coreText, "utf8")
    .digest("hex")
    .slice(0, 12);
  return [
    `<!-- test-policy:start checksum=${checksum} -->`,
    "## Test ownership policy (generated — do not hand-edit)",
    "",
    "Generated by `scripts/sync-agent-test-policy.mjs` from",
    "`docs/agents/testing-policy.md`. Read the full policy there before adding",
    "or materially changing a test; this block is a summary, not the source.",
    "",
    coreText,
    "",
    "<!-- test-policy:end -->",
  ].join("\n");
}

test("accepts a minimal fully-governed fixture", () => {
  const rootDir = createValidFixture();
  assert.deepEqual(checkTestPolicy(rootDir), []);
});

test("rejects a claim whose primary test cannot be found in its file", () => {
  const rootDir = createValidFixture();
  const claimsPath = path.join(rootDir, "verification/test-claims.json");
  const claims = JSON.parse(fs.readFileSync(claimsPath, "utf8"));
  claims.claims[0].primary.test = "does a different thing";
  fs.writeFileSync(claimsPath, JSON.stringify(claims));

  const violations = checkTestPolicy(rootDir);
  assert.ok(violations.some((v) => v.ruleId === "TG-TRACE"));
});

test("rejects a claim pointing at a file that does not exist", () => {
  const rootDir = createValidFixture();
  const claimsPath = path.join(rootDir, "verification/test-claims.json");
  const claims = JSON.parse(fs.readFileSync(claimsPath, "utf8"));
  claims.claims[0].primary.file = "packages/example/src/missing.test.ts";
  fs.writeFileSync(claimsPath, JSON.stringify(claims));

  const violations = checkTestPolicy(rootDir);
  assert.ok(
    violations.some(
      (v) => v.ruleId === "TG-TRACE" && v.message.includes("does not exist"),
    ),
  );
});

test("rejects duplicate claim ids", () => {
  const rootDir = createValidFixture();
  const claimsPath = path.join(rootDir, "verification/test-claims.json");
  const claims = JSON.parse(fs.readFileSync(claimsPath, "utf8"));
  claims.claims.push({ ...claims.claims[0] });
  fs.writeFileSync(claimsPath, JSON.stringify(claims));

  const violations = checkTestPolicy(rootDir);
  assert.ok(
    violations.some(
      (v) => v.ruleId === "TG-02" && v.message.includes("duplicate claim id"),
    ),
  );
});

test("rejects two claims sharing the same primary owner", () => {
  const rootDir = createValidFixture();
  const claimsPath = path.join(rootDir, "verification/test-claims.json");
  const claims = JSON.parse(fs.readFileSync(claimsPath, "utf8"));
  claims.claims.push({ ...claims.claims[0], id: "V-EXAMPLE-TWO" });
  fs.writeFileSync(claimsPath, JSON.stringify(claims));

  const violations = checkTestPolicy(rootDir);
  assert.ok(
    violations.some(
      (v) => v.ruleId === "TG-02" && v.message.includes("claimed as primary owner"),
    ),
  );
});

test("rejects a secondary owner with a generic uniqueProof", () => {
  const rootDir = createValidFixture();
  writeFile(rootDir, "e2e/example.spec.ts", `test("browser check", () => {});\n`);
  const claimsPath = path.join(rootDir, "verification/test-claims.json");
  const claims = JSON.parse(fs.readFileSync(claimsPath, "utf8"));
  claims.claims[0].secondary = [
    {
      file: "e2e/example.spec.ts",
      test: "browser check",
      boundary: "browser",
      uniqueProof: "for extra confidence",
    },
  ];
  fs.writeFileSync(claimsPath, JSON.stringify(claims));

  const violations = checkTestPolicy(rootDir);
  assert.ok(
    violations.some(
      (v) => v.ruleId === "TG-04" && v.message.includes("generic phrase"),
    ),
  );
});

test("rejects an expensive setup claim with no isolationReason", () => {
  const rootDir = createValidFixture();
  const claimsPath = path.join(rootDir, "verification/test-claims.json");
  const claims = JSON.parse(fs.readFileSync(claimsPath, "utf8"));
  claims.claims[0].setup = "db-isolated";
  fs.writeFileSync(claimsPath, JSON.stringify(claims));

  const violations = checkTestPolicy(rootDir);
  assert.ok(
    violations.some(
      (v) => v.ruleId === "TG-08" && v.message.includes("isolationReason"),
    ),
  );
});

test("rejects a direct createDisposableDatabase() call outside the allowlist", () => {
  const rootDir = createValidFixture();
  writeFile(
    rootDir,
    "packages/example/src/rogue.db.test.ts",
    `const db = await createDisposableDatabase();\n`,
  );

  const violations = checkTestPolicy(rootDir);
  assert.ok(
    violations.some(
      (v) => v.ruleId === "TG-08" && v.file === "packages/example/src/rogue.db.test.ts",
    ),
  );
});

test("ignores createDisposableDatabase mentioned only in a comment", () => {
  const rootDir = createValidFixture();
  writeFile(
    rootDir,
    "packages/example/src/note.db.test.ts",
    `// see createDisposableDatabase() for details\ntest("uses shared fixture", () => {});\n`,
  );

  const violations = checkTestPolicy(rootDir);
  assert.ok(!violations.some((v) => v.file === "packages/example/src/note.db.test.ts"));
});

test("rejects a drifted (hand-edited) adapter block", () => {
  const rootDir = createValidFixture();
  const agentsPath = path.join(rootDir, "AGENTS.md");
  fs.writeFileSync(
    agentsPath,
    fs.readFileSync(agentsPath, "utf8").replace("rule one", "hand-edited rule"),
  );

  const violations = checkTestPolicy(rootDir);
  assert.ok(
    violations.some((v) => v.ruleId === "ADAPTER-SYNC" && v.file === "AGENTS.md"),
  );
});

test("rejects a new test declaration that is neither governed nor in the legacy baseline", () => {
  const rootDir = createValidFixture();
  writeFile(
    rootDir,
    "packages/example/src/bar.test.ts",
    `test("a brand new untracked behavior", () => {});\n`,
  );

  const violations = checkTestPolicy(rootDir);
  assert.ok(
    violations.some(
      (v) =>
        v.ruleId === "TG-GOVERNANCE-BASELINE" &&
        v.message.includes("new ungoverned test declaration"),
    ),
  );
});

test("passes when a new declaration is recorded in the legacy baseline", () => {
  const rootDir = createValidFixture();
  writeFile(
    rootDir,
    "packages/example/src/bar.test.ts",
    `test("a tracked legacy behavior", () => {});\n`,
  );
  writeFile(
    rootDir,
    "verification/legacy-test-baseline.json",
    JSON.stringify(
      {
        schemaVersion: 1,
        generatedBy: "node scripts/generate-legacy-baseline.mjs --write",
        declarationCount: 1,
        declarations: [
          {
            file: "packages/example/src/bar.test.ts",
            test: "a tracked legacy behavior",
          },
        ],
      },
      null,
      2,
    ) + "\n",
  );

  const violations = checkTestPolicy(rootDir);
  assert.deepEqual(
    violations.filter((v) => v.ruleId === "TG-GOVERNANCE-BASELINE"),
    [],
  );
});

test("rejects a malformed eval scenario alongside other checks", () => {
  const rootDir = createValidFixture();
  const scenarioPath = path.join(
    rootDir,
    "verification/test-policy-evals/control-a.json",
  );
  const scenario = JSON.parse(fs.readFileSync(scenarioPath, "utf8"));
  scenario.expected.action = "not-a-real-action";
  fs.writeFileSync(scenarioPath, JSON.stringify(scenario));

  const violations = checkTestPolicy(rootDir);
  assert.ok(violations.some((v) => v.ruleId === "TAG-01-SCHEMA"));
});
