#!/usr/bin/env node

/**
 * Generates the Kysely `Database` interface from the committed schema snapshot.
 *
 * The types are generated rather than hand-written, and generated from the
 * snapshot rather than from a live connection. That gives one chain with no
 * weak link: the audit proves the snapshot matches a freshly migrated database,
 * this proves the types match the snapshot, and a drift test proves the
 * committed file matches what this produces. A hand-written interface could be
 * wrong in a way no test would notice until a query returned the wrong shape.
 *
 * Mutability is narrowed on purpose. Append-only tables get no updatable
 * column at all, so `updateTable("world_events")` is a compile error rather
 * than a code review comment. `episodes` may update exactly its two derived
 * embedding columns, which is the sole mutable exception the contract allows.
 *
 * Run `pnpm db:types` after `pnpm db:snapshot`, and read the diff.
 */

import { readFile, writeFile } from "node:fs/promises";
import process from "node:process";

const SNAPSHOT_PATH = new URL(
  "../packages/database-admin/schema-snapshot.json",
  import.meta.url,
);
const OUTPUT_PATH = new URL("../packages/database/src/schema.ts", import.meta.url);

/** Tables whose rows are never edited after they are written. */
const APPEND_ONLY = new Set([
  // Causal history
  "world_events",
  "belief_evidence",
  "relationship_changes",
  "claim_transmissions",
  "clue_discoveries",
  "case_attempts",
  "npc_interactions",
  "episode_references",
  "agent_runs",
  "town_resolutions",
  "case_board_entries",
  // Authored truth, frozen at materialization
  "story_entities",
  "actors",
  "npcs",
  "claims",
  "claim_relations",
  "world_facts",
  "case_solutions",
  "clues",
  "clue_claim_effects",
  "inspectables",
  "schema_migrations",
]);

/**
 * The one mutable exception in an otherwise immutable table: an embedding may
 * move from pending or failed to ready without changing what the NPC
 * experienced.
 */
const RESTRICTED_UPDATES = new Map([["episodes", ["embedding", "embedding_status"]]]);

const SCALARS = {
  uuid: "Uuid",
  bytea: "Sha256Bytes",
  "timestamp with time zone": "Utc",
  bigint: "number",
  integer: "number",
  numeric: "UsdCost",
  boolean: "boolean",
  jsonb: "JsonValue",
  vector: "Vector256",
  date: "BillingMonth",
  text: "string",
};

/**
 * Reads the closed domain out of a `col IN ('a'::STRING, …)` check.
 *
 * A column can appear in more than one `IN` list: `agent_runs.purpose` has its
 * domain check and, inside the contract-version check, a narrower list of the
 * two embedding purposes. The widest list is the domain; a narrower one is a
 * case within it, so taking the first match would have typed the column as its
 * own special case.
 */
export function domainUnionFor(column, constraints) {
  let widest = [];
  for (const definition of Object.values(constraints)) {
    for (const match of definition.matchAll(
      new RegExp(`\\b${column} IN \\(([^)]*)\\)`, "g"),
    )) {
      const values = [...match[1].matchAll(/'([^']*)'/g)].map((value) => value[1]);
      if (values.length > widest.length) widest = values;
    }
  }
  if (widest.length === 0) return undefined;
  return widest.map((value) => `"${value}"`).join(" | ");
}

export function typeFor(column, details, constraints) {
  const base =
    (details.type === "text" ? domainUnionFor(column, constraints) : undefined) ??
    SCALARS[details.type] ??
    "unknown";
  return details.nullable ? `${base} | null` : base;
}

function columnEntry(table, column, details, constraints) {
  const select = typeFor(column, details, constraints);
  const insert = details.default === null ? select : `${select} | undefined`;

  const restricted = RESTRICTED_UPDATES.get(table);
  const immutable =
    APPEND_ONLY.has(table) ||
    (restricted !== undefined && !restricted.includes(column));
  const update = immutable ? "never" : select;

  // A plain type is enough only when all three roles agree.
  if (select === insert && select === update) return `  ${column}: ${select};`;
  return `  ${column}: ColumnType<${select}, ${insert}, ${update}>;`;
}

function interfaceName(name) {
  return name
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

export function generate(snapshot) {
  const lines = [
    "/**",
    " * The Kysely database interface.",
    " *",
    " * Generated by `pnpm db:types` from",
    " * `packages/database-admin/schema-snapshot.json`. Do not edit by hand: the",
    " * drift test regenerates it and compares, so a manual change fails the",
    " * suite rather than silently disagreeing with the migrated schema.",
    " *",
    " * Append-only tables declare `never` for every update type, so editing",
    " * causal history is a compile error. `episodes` may update exactly its two",
    " * derived embedding columns.",
    " */",
    "",
    'import type { ColumnType } from "kysely";',
    "",
    "import type {",
    "  BillingMonth,",
    "  JsonValue,",
    "  Sha256Bytes,",
    "  UsdCost,",
    "  Utc,",
    "  Uuid,",
    "  Vector256,",
    '} from "./brands.js";',
    "",
  ];

  for (const [table, details] of Object.entries(snapshot.tables)) {
    lines.push(`export interface ${interfaceName(table)}Table {`);
    for (const [column, column_details] of Object.entries(details.columns)) {
      lines.push(columnEntry(table, column, column_details, details.constraints));
    }
    lines.push("}", "");
  }

  for (const [view, columns] of Object.entries(snapshot.viewColumns)) {
    lines.push(`/** Read-only. Inspection never writes. */`);
    lines.push(`export interface Inspection${interfaceName(view)}View {`);
    for (const [column, details] of Object.entries(columns)) {
      const select = typeFor(column, details, {});
      lines.push(`  ${column}: ColumnType<${select}, never, never>;`);
    }
    lines.push("}", "");
  }

  lines.push("export interface Database {");
  for (const table of Object.keys(snapshot.tables)) {
    lines.push(`  "public.${table}": ${interfaceName(table)}Table;`);
  }
  for (const view of Object.keys(snapshot.viewColumns)) {
    lines.push(`  "inspection.${view}": Inspection${interfaceName(view)}View;`);
  }
  lines.push("}", "");

  return lines.join("\n");
}

export async function readSnapshot() {
  return JSON.parse(await readFile(SNAPSHOT_PATH, "utf8"));
}

async function main() {
  const generated = generate(await readSnapshot());
  await writeFile(OUTPUT_PATH, generated, "utf8");
  console.log("Wrote packages/database/src/schema.ts");
}

if (process.argv[1]?.endsWith("db-types.mjs")) {
  await main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
