/**
 * The Kysely database interface.
 *
 * Generated by `pnpm db:types` from
 * `packages/database-admin/schema-snapshot.json`. Do not edit by hand: the
 * drift test regenerates it and compares, so a manual change fails the
 * suite rather than silently disagreeing with the migrated schema.
 *
 * Append-only tables declare `never` for every update type, so editing
 * causal history is a compile error. `episodes` may update exactly its two
 * derived embedding columns.
 */

import type { ColumnType } from "kysely";

import type {
  BillingMonth,
  JsonValue,
  Sha256Bytes,
  UsdCost,
  Utc,
  Uuid,
  Vector256,
} from "./brands.js";

export interface ActorsTable {
  actor_type: ColumnType<"player" | "npc", "player" | "npc", never>;
  created_at: ColumnType<Utc, Utc, never>;
  display_name: ColumnType<string, string, never>;
  display_name_normalized: ColumnType<string, string, never>;
  id: ColumnType<Uuid, Uuid, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface AgentRunsTable {
  ambient_job_execution_id: ColumnType<Uuid | null, Uuid | null, never>;
  cache_read_tokens: ColumnType<number, number, never>;
  cache_write_tokens: ColumnType<number, number, never>;
  created_at: ColumnType<Utc, Utc, never>;
  estimated_cost: ColumnType<UsdCost, UsdCost, never>;
  id: ColumnType<Uuid, Uuid, never>;
  inference_profile: ColumnType<string, string, never>;
  input_tokens: ColumnType<number, number, never>;
  latency_ms: ColumnType<number, number, never>;
  model: ColumnType<string, string, never>;
  outcome: ColumnType<"accepted" | "repaired" | "rejected" | "fallback" | "failed" | "superseded", "accepted" | "repaired" | "rejected" | "fallback" | "failed" | "superseded", never>;
  output_schema_version: ColumnType<string | null, string | null, never>;
  output_tokens: ColumnType<number, number, never>;
  player_action_id: ColumnType<Uuid | null, Uuid | null, never>;
  prompt_sha256: ColumnType<Sha256Bytes | null, Sha256Bytes | null, never>;
  prompt_version: ColumnType<string, string, never>;
  purpose: ColumnType<"claim_normalization" | "dialogue_selection" | "ambient_choice" | "structured_repair" | "episode_embedding" | "query_embedding", "claim_normalization" | "dialogue_selection" | "ambient_choice" | "structured_repair" | "episode_embedding" | "query_embedding", never>;
  target_prompt_version: ColumnType<string | null, string | null, never>;
  task_input_version: ColumnType<string | null, string | null, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
  validation_error_code: ColumnType<string | null, string | null, never>;
  validation_policy_version: ColumnType<string | null, string | null, never>;
  world_event_id: ColumnType<Uuid | null, Uuid | null, never>;
}

export interface AmbientJobExecutionsTable {
  action_count: number | null;
  attempt_count: ColumnType<number, number | undefined, number>;
  completed_at: Utc | null;
  created_at: Utc;
  error_code: string | null;
  id: Uuid;
  job_key: Uuid;
  outbox_id: Uuid;
  payload_hash: Sha256Bytes;
  processing_expires_at: Utc | null;
  processing_token: Uuid | null;
  status: "processing" | "completed" | "quarantined";
  town_id: Uuid;
  updated_at: Utc;
}

export interface ApiRateLimitsTable {
  bucket_kind: "model_action" | "player_view" | "town_creation" | "join";
  created_at: Utc;
  last_refill_at: Utc;
  scope_key: Sha256Bytes;
  scope_kind: "ip_hash" | "player" | "town";
  tokens_milli: number;
  updated_at: Utc;
}

export interface BeliefEvidenceTable {
  claim_id: ColumnType<Uuid, Uuid, never>;
  clue_id: ColumnType<Uuid | null, Uuid | null, never>;
  corroboration_threshold: ColumnType<number | null, number | null, never>;
  created_at: ColumnType<Utc, Utc, never>;
  episode_id: ColumnType<Uuid | null, Uuid | null, never>;
  event_id: ColumnType<Uuid, Uuid, never>;
  evidence_kind: ColumnType<"direct_observation" | "player_testimony" | "npc_testimony" | "physical_clue" | "corroboration" | "contradiction" | "source_reversal", "direct_observation" | "player_testimony" | "npc_testimony" | "physical_clue" | "corroboration" | "contradiction" | "source_reversal", never>;
  hop_count: ColumnType<number | null, number | null, never>;
  id: ColumnType<Uuid, Uuid, never>;
  independent_source_actor_id: ColumnType<Uuid | null, Uuid | null, never>;
  mirrors_evidence_id: ColumnType<Uuid | null, Uuid | null, never>;
  npc_id: ColumnType<Uuid, Uuid, never>;
  reverses_evidence_id: ColumnType<Uuid | null, Uuid | null, never>;
  rule_version: ColumnType<string, string, never>;
  signed_weight: ColumnType<number, number, never>;
  source_root_transmission_id: ColumnType<Uuid | null, Uuid | null, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
  transmission_id: ColumnType<Uuid | null, Uuid | null, never>;
  trust_snapshot: ColumnType<number | null, number | null, never>;
}

export interface CaseAttemptsTable {
  created_at: ColumnType<Utc, Utc, never>;
  event_id: ColumnType<Uuid, Uuid, never>;
  id: ColumnType<Uuid, Uuid, never>;
  location_entity_id: ColumnType<Uuid, Uuid, never>;
  location_entity_type: ColumnType<string, string | undefined, never>;
  motive_entity_id: ColumnType<Uuid, Uuid, never>;
  motive_entity_type: ColumnType<string, string | undefined, never>;
  outcome: ColumnType<"incorrect" | "correct", "incorrect" | "correct", never>;
  player_action_id: ColumnType<Uuid, Uuid, never>;
  player_id: ColumnType<Uuid, Uuid, never>;
  suspect_entity_id: ColumnType<Uuid, Uuid, never>;
  suspect_entity_type: ColumnType<string, string | undefined, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface CaseBoardEntriesTable {
  claim_id: ColumnType<Uuid | null, Uuid | null, never>;
  clue_id: ColumnType<Uuid | null, Uuid | null, never>;
  contributed_by_player_id: ColumnType<Uuid, Uuid, never>;
  created_at: ColumnType<Utc, Utc, never>;
  entry_kind: ColumnType<"verified_evidence" | "testimony" | "hearsay" | "note", "verified_evidence" | "testimony" | "hearsay" | "note", never>;
  id: ColumnType<Uuid, Uuid, never>;
  note_text: ColumnType<string | null, string | null, never>;
  source_event_id: ColumnType<Uuid, Uuid, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
  transmission_id: ColumnType<Uuid | null, Uuid | null, never>;
  verification_status: ColumnType<"verified_physical" | "attributed_testimony" | "attributed_hearsay" | "unverified_player_note", "verified_physical" | "attributed_testimony" | "attributed_hearsay" | "unverified_player_note", never>;
}

export interface CaseSolutionsTable {
  created_at: ColumnType<Utc, Utc, never>;
  culprit_entity_id: ColumnType<Uuid, Uuid, never>;
  culprit_entity_type: ColumnType<string, string | undefined, never>;
  location_entity_id: ColumnType<Uuid, Uuid, never>;
  location_entity_type: ColumnType<string, string | undefined, never>;
  motive_entity_id: ColumnType<Uuid, Uuid, never>;
  motive_entity_type: ColumnType<string, string | undefined, never>;
  required_item_entity_type: ColumnType<string, string | undefined, never>;
  required_item_id: ColumnType<Uuid, Uuid, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface ClaimDraftsTable {
  alleged_source_actor_id: Uuid | null;
  confirmed_by_action_id: Uuid | null;
  confirmed_claim_id: Uuid | null;
  context_key: string;
  created_at: Utc;
  expires_at: Utc;
  id: Uuid;
  normalization_action_id: Uuid;
  normalized_key: string;
  object_entity_id: Uuid;
  object_entity_type: string;
  original_text: string;
  player_id: Uuid;
  polarity: "positive" | "negative";
  predicate: "was_at" | "moved" | "damaged" | "is_at" | "acted_for";
  status: "pending" | "confirmed" | "cancelled" | "expired";
  subject_entity_id: Uuid;
  subject_entity_type: string;
  target_npc_id: Uuid;
  town_id: Uuid;
  updated_at: Utc;
  visit_id: Uuid;
}

export interface ClaimRelationsTable {
  claim_a_id: ColumnType<Uuid, Uuid, never>;
  claim_b_id: ColumnType<Uuid, Uuid, never>;
  created_at: ColumnType<Utc, Utc, never>;
  relation_kind: ColumnType<"contradicts" | "entails", "contradicts" | "entails", never>;
  rule_version: ColumnType<string, string, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface ClaimTransmissionsTable {
  alleged_source_actor_id: ColumnType<Uuid | null, Uuid | null, never>;
  claim_id: ColumnType<Uuid, Uuid, never>;
  created_at: ColumnType<Utc, Utc, never>;
  event_id: ColumnType<Uuid, Uuid, never>;
  hop_count: ColumnType<number, number, never>;
  id: ColumnType<Uuid, Uuid, never>;
  interaction_id: ColumnType<Uuid | null, Uuid | null, never>;
  ordinal: ColumnType<number, number, never>;
  parent_eligible: ColumnType<boolean, boolean, never>;
  parent_is_eligible: ColumnType<boolean | null, boolean | null, never>;
  parent_transmission_id: ColumnType<Uuid | null, Uuid | null, never>;
  recipient_actor_id: ColumnType<Uuid, Uuid, never>;
  recipient_actor_type: ColumnType<"player" | "npc", "player" | "npc", never>;
  root_transmission_id: ColumnType<Uuid, Uuid, never>;
  source_episode_id: ColumnType<Uuid | null, Uuid | null, never>;
  source_kind: ColumnType<"original_assertion" | "direct_observation" | "repeated_testimony" | "alleged_hearsay", "original_assertion" | "direct_observation" | "repeated_testimony" | "alleged_hearsay", never>;
  speaker_actor_id: ColumnType<Uuid, Uuid, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface ClaimsTable {
  context_key: ColumnType<string, string, never>;
  created_at: ColumnType<Utc, Utc, never>;
  id: ColumnType<Uuid, Uuid, never>;
  normalized_key: ColumnType<string, string, never>;
  object_entity_id: ColumnType<Uuid, Uuid, never>;
  object_entity_type: ColumnType<string, string, never>;
  polarity: ColumnType<"positive" | "negative", "positive" | "negative", never>;
  predicate: ColumnType<"was_at" | "moved" | "damaged" | "is_at" | "acted_for", "was_at" | "moved" | "damaged" | "is_at" | "acted_for", never>;
  subject_entity_id: ColumnType<Uuid, Uuid, never>;
  subject_entity_type: ColumnType<string, string, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface ClueClaimEffectsTable {
  claim_id: ColumnType<Uuid, Uuid, never>;
  clue_id: ColumnType<Uuid, Uuid, never>;
  created_at: ColumnType<Utc, Utc, never>;
  effect_kind: ColumnType<"supports" | "contradicts", "supports" | "contradicts", never>;
  rule_version: ColumnType<string, string, never>;
  signed_weight: ColumnType<number, number, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface ClueDiscoveriesTable {
  clue_id: ColumnType<Uuid, Uuid, never>;
  created_at: ColumnType<Utc, Utc, never>;
  event_id: ColumnType<Uuid, Uuid, never>;
  id: ColumnType<Uuid, Uuid, never>;
  player_id: ColumnType<Uuid, Uuid, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface CluesTable {
  clue_key: ColumnType<string, string, never>;
  clue_kind: ColumnType<"physical_trace" | "document" | "object_state", "physical_trace" | "document" | "object_state", never>;
  content_key: ColumnType<string, string, never>;
  created_at: ColumnType<Utc, Utc, never>;
  id: ColumnType<Uuid, Uuid, never>;
  inspectable_id: ColumnType<Uuid, Uuid, never>;
  required_for_resolution: ColumnType<boolean, boolean, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface EpisodeReferencesTable {
  claim_id: ColumnType<Uuid | null, Uuid | null, never>;
  created_at: ColumnType<Utc, Utc, never>;
  entity_id: ColumnType<Uuid | null, Uuid | null, never>;
  episode_id: ColumnType<Uuid, Uuid, never>;
  id: ColumnType<Uuid, Uuid | undefined, never>;
  reference_kind: ColumnType<"participant" | "location" | "item" | "motive" | "claim", "participant" | "location" | "item" | "motive" | "claim", never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface EpisodesTable {
  created_at: ColumnType<Utc, Utc, never>;
  embedding: Vector256 | null;
  embedding_status: "pending" | "ready" | "failed";
  episode_kind: ColumnType<"direct_observation" | "heard_claim" | "player_interaction" | "promise_consequence" | "item_transfer" | "world_consequence", "direct_observation" | "heard_claim" | "player_interaction" | "promise_consequence" | "item_transfer" | "world_consequence", never>;
  event_id: ColumnType<Uuid, Uuid, never>;
  id: ColumnType<Uuid, Uuid, never>;
  importance: ColumnType<number, number, never>;
  npc_id: ColumnType<Uuid, Uuid, never>;
  occurred_at: ColumnType<Utc, Utc, never>;
  summary: ColumnType<string, string, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
  updated_at: ColumnType<Utc, Utc, never>;
}

export interface InspectablesTable {
  content_key: ColumnType<string, string, never>;
  created_at: ColumnType<Utc, Utc, never>;
  display_name: ColumnType<string, string, never>;
  enabled: ColumnType<boolean, boolean | undefined, never>;
  gate_key: ColumnType<string | null, string | null, never>;
  id: ColumnType<Uuid, Uuid, never>;
  inspectable_key: ColumnType<string, string, never>;
  linked_entity_id: ColumnType<Uuid | null, Uuid | null, never>;
  linked_entity_type: ColumnType<string | null, string | null, never>;
  location_entity_id: ColumnType<Uuid, Uuid, never>;
  location_entity_type: ColumnType<string, string | undefined, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
  updated_at: ColumnType<Utc, Utc, never>;
}

export interface ItemsTable {
  created_at: Utc;
  entity_type: ColumnType<string, string | undefined, string>;
  held_by_actor_id: Uuid | null;
  id: Uuid;
  location_entity_id: Uuid | null;
  location_entity_type: string | null;
  portable: boolean;
  revealed_event_id: Uuid | null;
  revision: ColumnType<number, number | undefined, number>;
  town_id: Uuid;
  updated_at: Utc;
}

export interface JoinRequestsTable {
  attempt_count: ColumnType<number, number | undefined, number>;
  bootstrap_confirmed_at: Utc | null;
  completed_at: Utc | null;
  created_at: Utc;
  error_code: string | null;
  idempotency_key: Uuid;
  initial_visit_id: Uuid | null;
  join_secret_hash: Sha256Bytes | null;
  player_id: Uuid | null;
  processing_expires_at: Utc | null;
  processing_token: Uuid | null;
  replay_closed_at: Utc | null;
  replay_closed_reason: "confirmed" | "expired" | "exhausted" | null;
  replay_expires_at: Utc | null;
  request_hash: Sha256Bytes;
  response_payload: JsonValue | null;
  response_status: number | null;
  session_issue_count: ColumnType<number, number | undefined, number>;
  status: "processing" | "completed" | "failed";
  town_id: Uuid;
  updated_at: Utc;
}

export interface ModelCostReservationsTable {
  actual_cost: UsdCost | null;
  agent_run_id: Uuid | null;
  ambient_job_execution_id: Uuid | null;
  attempt_ordinal: number;
  billing_month: BillingMonth;
  created_at: Utc;
  id: Uuid;
  inference_profile: string;
  maximum_cost: UsdCost;
  model: string;
  non_game_operation_key: string | null;
  player_action_id: Uuid | null;
  price_version: string;
  purpose: "claim_normalization" | "dialogue_selection" | "ambient_choice" | "structured_repair" | "episode_embedding" | "query_embedding";
  settled_at: Utc | null;
  status: "reserved" | "settled" | "released";
  town_id: Uuid | null;
  world_event_id: Uuid | null;
}

export interface NpcBeliefsTable {
  claim_id: Uuid;
  created_at: Utc;
  label: "convinced" | "leaning" | "doubtful";
  npc_id: Uuid;
  revision: ColumnType<number, number | undefined, number>;
  score: number;
  town_id: Uuid;
  updated_at: Utc;
  updated_event_id: Uuid;
}

export interface NpcContactEdgesTable {
  created_at: Utc;
  enabled: ColumnType<boolean, boolean | undefined, boolean>;
  from_npc_id: Uuid;
  to_npc_id: Uuid;
  town_id: Uuid;
  trust_score: number;
  updated_at: Utc;
}

export interface NpcInteractionsTable {
  created_at: ColumnType<Utc, Utc, never>;
  event_id: ColumnType<Uuid, Uuid, never>;
  id: ColumnType<Uuid, Uuid, never>;
  input_kind: ColumnType<"ask" | "tell" | "show" | "give" | "promise", "ask" | "tell" | "show" | "give" | "promise", never>;
  npc_id: ColumnType<Uuid, Uuid, never>;
  npc_text: ColumnType<string, string, never>;
  player_action_id: ColumnType<Uuid, Uuid, never>;
  player_id: ColumnType<Uuid, Uuid, never>;
  player_text: ColumnType<string | null, string | null, never>;
  response_mode: ColumnType<"selected" | "repaired" | "fallback" | "authored", "selected" | "repaired" | "fallback" | "authored", never>;
  town_id: ColumnType<Uuid, Uuid, never>;
  visit_id: ColumnType<Uuid, Uuid, never>;
}

export interface NpcPlayerRelationshipsTable {
  created_at: Utc;
  npc_id: Uuid;
  player_id: Uuid;
  revision: ColumnType<number, number | undefined, number>;
  suspicion_score: ColumnType<number, number | undefined, number>;
  town_id: Uuid;
  trust_score: ColumnType<number, number | undefined, number>;
  updated_at: Utc;
  updated_event_id: Uuid | null;
}

export interface NpcsTable {
  actor_type: ColumnType<string, string | undefined, never>;
  character_entity_id: ColumnType<Uuid, Uuid, never>;
  character_entity_type: ColumnType<string, string | undefined, never>;
  created_at: ColumnType<Utc, Utc, never>;
  id: ColumnType<Uuid, Uuid, never>;
  location_entity_id: ColumnType<Uuid, Uuid, never>;
  location_entity_type: ColumnType<string, string | undefined, never>;
  profile_key: ColumnType<string, string, never>;
  profile_version: ColumnType<string, string, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface OutboxTable {
  after_event_sequence: number;
  created_at: Utc;
  delivery_status: "pending" | "sending" | "sent" | "abandoned";
  id: Uuid;
  job_key: Uuid;
  job_type: "ambient_tick";
  last_error_code: string | null;
  next_send_at: Utc;
  not_before: Utc;
  payload: JsonValue;
  payload_hash: Sha256Bytes;
  send_attempt_count: ColumnType<number, number | undefined, number>;
  send_expires_at: Utc | null;
  send_token: Uuid | null;
  sent_at: Utc | null;
  source_event_id: Uuid;
  through_event_sequence: number;
  town_id: Uuid;
  transition_deadline_at: Utc;
  updated_at: Utc;
  visit_id: Uuid;
}

export interface PlayerActionsTable {
  action_kind: "start_visit" | "travel" | "inspect" | "ask" | "normalize_claim" | "tell" | "show" | "give" | "accept_promise" | "add_note" | "leave" | "accuse" | "resolve";
  attempt_count: ColumnType<number, number | undefined, number>;
  completed_at: Utc | null;
  created_at: Utc;
  error_code: string | null;
  id: Uuid;
  idempotency_key: Uuid;
  outcome: "applied" | "no_change" | "denied" | null;
  player_id: Uuid;
  processing_expires_at: Utc | null;
  processing_token: Uuid | null;
  request_hash: Sha256Bytes;
  request_payload: JsonValue;
  response_payload: JsonValue | null;
  response_status: number | null;
  retry_after_at: Utc | null;
  status: "processing" | "retryable" | "completed" | "failed";
  target_actor_id: Uuid | null;
  target_entity_id: Uuid | null;
  town_id: Uuid;
  updated_at: Utc;
  visit_id: Uuid | null;
}

export interface PlayerCapabilitiesTable {
  capability_key: string;
  created_at: Utc;
  granted_event_id: Uuid;
  id: Uuid;
  player_id: Uuid;
  revoked_event_id: Uuid | null;
  status: "granted" | "revoked";
  town_id: Uuid;
  updated_at: Utc;
}

export interface PlayerSessionsTable {
  created_at: Utc;
  id: Uuid;
  join_request_id: Uuid;
  last_cookie_issued_at: Utc;
  player_id: Uuid;
  status: "active" | "revoked";
  token_hash: Sha256Bytes;
  town_id: Uuid;
  updated_at: Utc;
}

export interface PlayerVisitsTable {
  current_location_entity_id: Uuid;
  current_location_entity_type: ColumnType<string, string | undefined, string>;
  end_reason: "left_town" | "town_resolved" | null;
  end_revision: number | null;
  ended_at: Utc | null;
  ended_by_action_id: Uuid | null;
  id: Uuid;
  player_id: Uuid;
  start_revision: number;
  started_at: Utc;
  started_by_action_id: Uuid;
  status: "active" | "ended";
  town_id: Uuid;
}

export interface PlayersTable {
  actor_type: ColumnType<string, string | undefined, string>;
  created_at: Utc;
  id: Uuid;
  last_seen_at: Utc;
  town_id: Uuid;
  updated_at: Utc;
}

export interface PromisesTable {
  accepted_event_id: Uuid;
  created_at: Utc;
  id: Uuid;
  item_id: Uuid | null;
  kind: "keep_secret" | "return_item";
  npc_id: Uuid;
  player_id: Uuid;
  protected_claim_id: Uuid | null;
  resolved_event_id: Uuid | null;
  status: "active" | "fulfilled" | "broken";
  terms_version: string;
  town_id: Uuid;
  updated_at: Utc;
}

export interface RelationshipChangesTable {
  claim_id: ColumnType<Uuid | null, Uuid | null, never>;
  clue_id: ColumnType<Uuid | null, Uuid | null, never>;
  created_at: ColumnType<Utc, Utc, never>;
  event_id: ColumnType<Uuid, Uuid, never>;
  id: ColumnType<Uuid, Uuid, never>;
  item_id: ColumnType<Uuid | null, Uuid | null, never>;
  npc_id: ColumnType<Uuid, Uuid, never>;
  player_id: ColumnType<Uuid, Uuid, never>;
  promise_id: ColumnType<Uuid | null, Uuid | null, never>;
  reason_kind: ColumnType<"verified_testimony" | "evidence_presented" | "requested_item_given" | "promise_fulfilled" | "lie_established" | "promise_broken", "verified_testimony" | "evidence_presented" | "requested_item_given" | "promise_fulfilled" | "lie_established" | "promise_broken", never>;
  rule_version: ColumnType<string, string, never>;
  source_root_transmission_id: ColumnType<Uuid | null, Uuid | null, never>;
  suspicion_delta: ColumnType<number, number, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
  trust_delta: ColumnType<number, number, never>;
}

export interface SchemaMigrationsTable {
  applied_at: ColumnType<Utc, Utc | undefined, never>;
  checksum: ColumnType<string, string, never>;
  name: ColumnType<string, string, never>;
  version: ColumnType<string, string, never>;
}

export interface StoryEntitiesTable {
  content_key: ColumnType<string, string, never>;
  created_at: ColumnType<Utc, Utc, never>;
  display_name: ColumnType<string, string, never>;
  entity_key: ColumnType<string, string, never>;
  entity_type: ColumnType<"character" | "location" | "item" | "motive", "character" | "location" | "item" | "motive", never>;
  id: ColumnType<Uuid, Uuid, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface TownCreationRequestsTable {
  attempt_count: ColumnType<number, number | undefined, number>;
  completed_at: Utc | null;
  content_version: string;
  created_at: Utc;
  error_code: string | null;
  idempotency_key: Uuid;
  processing_expires_at: Utc | null;
  processing_token: Uuid | null;
  request_hash: Sha256Bytes;
  response_payload: JsonValue | null;
  response_status: number | null;
  security_key_version: string;
  status: "processing" | "completed" | "failed";
  town_id: Uuid | null;
  updated_at: Utc;
}

export interface TownResolutionsTable {
  case_attempt_id: ColumnType<Uuid, Uuid, never>;
  choice: ColumnType<"expose_cover_up" | "restore_bell_quietly", "expose_cover_up" | "restore_bell_quietly", never>;
  chosen_by_player_id: ColumnType<Uuid, Uuid, never>;
  created_at: ColumnType<Utc, Utc, never>;
  event_id: ColumnType<Uuid, Uuid, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface TownsTable {
  ambient_scheduled_through_sequence: ColumnType<number, number | undefined, number>;
  content_version: string;
  created_at: Utc;
  id: Uuid;
  invite_token_hash: Sha256Bytes;
  last_event_sequence: ColumnType<number, number | undefined, number>;
  resolution_owner_player_id: Uuid | null;
  resolution_reservation_expires_at: Utc | null;
  resolved_at: Utc | null;
  revision: ColumnType<number, number | undefined, number>;
  status: "active" | "awaiting_resolution" | "resolved" | "retired";
  updated_at: Utc;
  winning_case_attempt_id: Uuid | null;
}

export interface WorldEventsTable {
  actor_id: ColumnType<Uuid | null, Uuid | null, never>;
  ambient_eligible: ColumnType<boolean, boolean, never>;
  ambient_job_execution_id: ColumnType<Uuid | null, Uuid | null, never>;
  claim_id: ColumnType<Uuid | null, Uuid | null, never>;
  clue_id: ColumnType<Uuid | null, Uuid | null, never>;
  created_at: ColumnType<Utc, Utc, never>;
  effect_index: ColumnType<number, number, never>;
  effect_key: ColumnType<string, string, never>;
  event_type: ColumnType<"authored_observation" | "visit_started" | "travelled" | "inspected" | "clue_discovered" | "npc_interaction" | "claim_transmitted" | "evidence_shown" | "item_transferred" | "item_relocated" | "promise_accepted" | "promise_fulfilled" | "promise_broken" | "capability_changed" | "note_added" | "visit_ended" | "relationship_changed" | "source_discredited" | "case_attempted" | "case_resolved", "authored_observation" | "visit_started" | "travelled" | "inspected" | "clue_discovered" | "npc_interaction" | "claim_transmitted" | "evidence_shown" | "item_transferred" | "item_relocated" | "promise_accepted" | "promise_fulfilled" | "promise_broken" | "capability_changed" | "note_added" | "visit_ended" | "relationship_changed" | "source_discredited" | "case_attempted" | "case_resolved", never>;
  id: ColumnType<Uuid, Uuid, never>;
  location_entity_id: ColumnType<Uuid | null, Uuid | null, never>;
  occurred_at: ColumnType<Utc, Utc, never>;
  origin_kind: ColumnType<"player_action" | "ambient_job" | "system_seed", "player_action" | "ambient_job" | "system_seed", never>;
  payload: ColumnType<JsonValue, JsonValue, never>;
  player_action_id: ColumnType<Uuid | null, Uuid | null, never>;
  promise_id: ColumnType<Uuid | null, Uuid | null, never>;
  sequence_no: ColumnType<number, number, never>;
  subject_entity_id: ColumnType<Uuid | null, Uuid | null, never>;
  target_actor_id: ColumnType<Uuid | null, Uuid | null, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
}

export interface WorldFactsTable {
  claim_id: ColumnType<Uuid, Uuid, never>;
  created_at: ColumnType<Utc, Utc, never>;
  fact_key: ColumnType<string, string, never>;
  id: ColumnType<Uuid, Uuid, never>;
  town_id: ColumnType<Uuid, Uuid, never>;
  visibility: ColumnType<"hidden" | "discoverable" | "public", "hidden" | "discoverable" | "public", never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionAccessOperationsView {
  attempt_count: ColumnType<number | null, never, never>;
  counter: ColumnType<number | null, never, never>;
  created_at: ColumnType<Utc | null, never, never>;
  detail: ColumnType<string | null, never, never>;
  error_code: ColumnType<string | null, never, never>;
  operation_key: ColumnType<string | null, never, never>;
  operation_kind: ColumnType<string | null, never, never>;
  status: ColumnType<string | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionAgentRunsView {
  agent_run_id: ColumnType<Uuid | null, never, never>;
  cache_read_tokens: ColumnType<number | null, never, never>;
  cache_write_tokens: ColumnType<number | null, never, never>;
  created_at: ColumnType<Utc | null, never, never>;
  estimated_cost: ColumnType<UsdCost | null, never, never>;
  event_sequence: ColumnType<number | null, never, never>;
  inference_profile: ColumnType<string | null, never, never>;
  input_tokens: ColumnType<number | null, never, never>;
  latency_ms: ColumnType<number | null, never, never>;
  model: ColumnType<string | null, never, never>;
  outcome: ColumnType<string | null, never, never>;
  output_schema_version: ColumnType<string | null, never, never>;
  output_tokens: ColumnType<number | null, never, never>;
  price_version: ColumnType<string | null, never, never>;
  prompt_version: ColumnType<string | null, never, never>;
  purpose: ColumnType<string | null, never, never>;
  reservation_status: ColumnType<string | null, never, never>;
  reserved_maximum_cost: ColumnType<UsdCost | null, never, never>;
  settled_cost: ColumnType<UsdCost | null, never, never>;
  target_prompt_version: ColumnType<string | null, never, never>;
  task_input_version: ColumnType<string | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
  validation_error_code: ColumnType<string | null, never, never>;
  validation_policy_version: ColumnType<string | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionAmbientJobsView {
  action_count: ColumnType<number | null, never, never>;
  after_event_sequence: ColumnType<number | null, never, never>;
  completed_at: ColumnType<Utc | null, never, never>;
  delivery_error_code: ColumnType<string | null, never, never>;
  delivery_status: ColumnType<string | null, never, never>;
  execution_attempt_count: ColumnType<number | null, never, never>;
  execution_error_code: ColumnType<string | null, never, never>;
  execution_status: ColumnType<string | null, never, never>;
  job_key: ColumnType<Uuid | null, never, never>;
  job_type: ColumnType<string | null, never, never>;
  not_before: ColumnType<Utc | null, never, never>;
  send_attempt_count: ColumnType<number | null, never, never>;
  sent_at: ColumnType<Utc | null, never, never>;
  source_event_sequence: ColumnType<number | null, never, never>;
  through_event_sequence: ColumnType<number | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
  transition_deadline_at: ColumnType<Utc | null, never, never>;
  visit_id: ColumnType<Uuid | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionBeliefEvidenceView {
  claim_key: ColumnType<string | null, never, never>;
  clue_key: ColumnType<string | null, never, never>;
  corroboration_threshold: ColumnType<number | null, never, never>;
  created_at: ColumnType<Utc | null, never, never>;
  event_sequence: ColumnType<number | null, never, never>;
  event_type: ColumnType<string | null, never, never>;
  evidence_kind: ColumnType<string | null, never, never>;
  hop_count: ColumnType<number | null, never, never>;
  independent_source_name: ColumnType<string | null, never, never>;
  mirrors_evidence_id: ColumnType<Uuid | null, never, never>;
  npc_name: ColumnType<string | null, never, never>;
  reverses_evidence_id: ColumnType<Uuid | null, never, never>;
  rule_version: ColumnType<string | null, never, never>;
  signed_weight: ColumnType<number | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
  trust_snapshot: ColumnType<number | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionCaseProgressView {
  created_at: ColumnType<Utc | null, never, never>;
  event_sequence: ColumnType<number | null, never, never>;
  outcome: ColumnType<string | null, never, never>;
  player_name: ColumnType<string | null, never, never>;
  progress_kind: ColumnType<string | null, never, never>;
  required_for_resolution: ColumnType<boolean | null, never, never>;
  subject_key: ColumnType<string | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionClaimPathsView {
  alleged_source_name: ColumnType<string | null, never, never>;
  claim_key: ColumnType<string | null, never, never>;
  created_at: ColumnType<Utc | null, never, never>;
  event_sequence: ColumnType<number | null, never, never>;
  hop_count: ColumnType<number | null, never, never>;
  ordinal: ColumnType<number | null, never, never>;
  origin_kind: ColumnType<string | null, never, never>;
  parent_transmission_id: ColumnType<Uuid | null, never, never>;
  recipient_actor_type: ColumnType<string | null, never, never>;
  recipient_name: ColumnType<string | null, never, never>;
  root_transmission_id: ColumnType<Uuid | null, never, never>;
  source_kind: ColumnType<string | null, never, never>;
  speaker_name: ColumnType<string | null, never, never>;
  speaker_type: ColumnType<string | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
  transmission_id: ColumnType<Uuid | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionIdempotencyStatusView {
  attempt_count: ColumnType<number | null, never, never>;
  completed_at: ColumnType<Utc | null, never, never>;
  created_at: ColumnType<Utc | null, never, never>;
  effect_count: ColumnType<number | null, never, never>;
  operation_id: ColumnType<Uuid | null, never, never>;
  operation_key: ColumnType<string | null, never, never>;
  operation_kind: ColumnType<string | null, never, never>;
  operation_subkind: ColumnType<string | null, never, never>;
  outcome: ColumnType<string | null, never, never>;
  processing_expires_at: ColumnType<Utc | null, never, never>;
  retry_after_at: ColumnType<Utc | null, never, never>;
  status: ColumnType<string | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionNpcBeliefsView {
  claim_key: ColumnType<string | null, never, never>;
  context_key: ColumnType<string | null, never, never>;
  label: ColumnType<string | null, never, never>;
  npc_key: ColumnType<string | null, never, never>;
  npc_name: ColumnType<string | null, never, never>;
  object_key: ColumnType<string | null, never, never>;
  polarity: ColumnType<string | null, never, never>;
  predicate: ColumnType<string | null, never, never>;
  revision: ColumnType<number | null, never, never>;
  score: ColumnType<number | null, never, never>;
  subject_key: ColumnType<string | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
  updated_at: ColumnType<Utc | null, never, never>;
  updated_event_sequence: ColumnType<number | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionObjectHistoryView {
  held_by_name: ColumnType<string | null, never, never>;
  item_key: ColumnType<string | null, never, never>;
  item_name: ColumnType<string | null, never, never>;
  location_key: ColumnType<string | null, never, never>;
  portable: ColumnType<boolean | null, never, never>;
  revealed_event_sequence: ColumnType<number | null, never, never>;
  revision: ColumnType<number | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
  updated_at: ColumnType<Utc | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionObjectiveTruthView {
  detail_key: ColumnType<string | null, never, never>;
  secondary_key: ColumnType<string | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
  truth_key: ColumnType<string | null, never, never>;
  truth_kind: ColumnType<string | null, never, never>;
  visibility: ColumnType<string | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionPromiseStatusView {
  accepted_event_sequence: ColumnType<number | null, never, never>;
  created_at: ColumnType<Utc | null, never, never>;
  item_key: ColumnType<string | null, never, never>;
  kind: ColumnType<string | null, never, never>;
  npc_name: ColumnType<string | null, never, never>;
  player_name: ColumnType<string | null, never, never>;
  promise_id: ColumnType<Uuid | null, never, never>;
  protected_claim_key: ColumnType<string | null, never, never>;
  resolved_event_sequence: ColumnType<number | null, never, never>;
  status: ColumnType<string | null, never, never>;
  terms_version: ColumnType<string | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
  updated_at: ColumnType<Utc | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionRelationshipTimelineView {
  claim_key: ColumnType<string | null, never, never>;
  clue_key: ColumnType<string | null, never, never>;
  created_at: ColumnType<Utc | null, never, never>;
  event_sequence: ColumnType<number | null, never, never>;
  item_key: ColumnType<string | null, never, never>;
  npc_name: ColumnType<string | null, never, never>;
  player_name: ColumnType<string | null, never, never>;
  promise_id: ColumnType<Uuid | null, never, never>;
  reason_kind: ColumnType<string | null, never, never>;
  rule_version: ColumnType<string | null, never, never>;
  suspicion_delta: ColumnType<number | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
  trust_delta: ColumnType<number | null, never, never>;
}

/** Read-only. Inspection never writes. */
export interface InspectionWorldEventTimelineView {
  actor_name: ColumnType<string | null, never, never>;
  ambient_eligible: ColumnType<boolean | null, never, never>;
  claim_key: ColumnType<string | null, never, never>;
  clue_key: ColumnType<string | null, never, never>;
  effect_index: ColumnType<number | null, never, never>;
  effect_key: ColumnType<string | null, never, never>;
  event_type: ColumnType<string | null, never, never>;
  location_entity_key: ColumnType<string | null, never, never>;
  occurred_at: ColumnType<Utc | null, never, never>;
  origin_kind: ColumnType<string | null, never, never>;
  promise_id: ColumnType<Uuid | null, never, never>;
  sequence_no: ColumnType<number | null, never, never>;
  subject_entity_key: ColumnType<string | null, never, never>;
  target_actor_name: ColumnType<string | null, never, never>;
  town_id: ColumnType<Uuid | null, never, never>;
}

export interface Database {
  "public.actors": ActorsTable;
  "public.agent_runs": AgentRunsTable;
  "public.ambient_job_executions": AmbientJobExecutionsTable;
  "public.api_rate_limits": ApiRateLimitsTable;
  "public.belief_evidence": BeliefEvidenceTable;
  "public.case_attempts": CaseAttemptsTable;
  "public.case_board_entries": CaseBoardEntriesTable;
  "public.case_solutions": CaseSolutionsTable;
  "public.claim_drafts": ClaimDraftsTable;
  "public.claim_relations": ClaimRelationsTable;
  "public.claim_transmissions": ClaimTransmissionsTable;
  "public.claims": ClaimsTable;
  "public.clue_claim_effects": ClueClaimEffectsTable;
  "public.clue_discoveries": ClueDiscoveriesTable;
  "public.clues": CluesTable;
  "public.episode_references": EpisodeReferencesTable;
  "public.episodes": EpisodesTable;
  "public.inspectables": InspectablesTable;
  "public.items": ItemsTable;
  "public.join_requests": JoinRequestsTable;
  "public.model_cost_reservations": ModelCostReservationsTable;
  "public.npc_beliefs": NpcBeliefsTable;
  "public.npc_contact_edges": NpcContactEdgesTable;
  "public.npc_interactions": NpcInteractionsTable;
  "public.npc_player_relationships": NpcPlayerRelationshipsTable;
  "public.npcs": NpcsTable;
  "public.outbox": OutboxTable;
  "public.player_actions": PlayerActionsTable;
  "public.player_capabilities": PlayerCapabilitiesTable;
  "public.player_sessions": PlayerSessionsTable;
  "public.player_visits": PlayerVisitsTable;
  "public.players": PlayersTable;
  "public.promises": PromisesTable;
  "public.relationship_changes": RelationshipChangesTable;
  "public.schema_migrations": SchemaMigrationsTable;
  "public.story_entities": StoryEntitiesTable;
  "public.town_creation_requests": TownCreationRequestsTable;
  "public.town_resolutions": TownResolutionsTable;
  "public.towns": TownsTable;
  "public.world_events": WorldEventsTable;
  "public.world_facts": WorldFactsTable;
  "inspection.access_operations": InspectionAccessOperationsView;
  "inspection.agent_runs": InspectionAgentRunsView;
  "inspection.ambient_jobs": InspectionAmbientJobsView;
  "inspection.belief_evidence": InspectionBeliefEvidenceView;
  "inspection.case_progress": InspectionCaseProgressView;
  "inspection.claim_paths": InspectionClaimPathsView;
  "inspection.idempotency_status": InspectionIdempotencyStatusView;
  "inspection.npc_beliefs": InspectionNpcBeliefsView;
  "inspection.object_history": InspectionObjectHistoryView;
  "inspection.objective_truth": InspectionObjectiveTruthView;
  "inspection.promise_status": InspectionPromiseStatusView;
  "inspection.relationship_timeline": InspectionRelationshipTimelineView;
  "inspection.world_event_timeline": InspectionWorldEventTimelineView;
}
