import { readFile } from "node:fs/promises";

import {
  createDisposableDatabase,
  shouldRunDatabaseTests,
  type DisposableDatabase,
} from "@the-town-remembers/test-support/database";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import {
  ACCEPTED_TABLES,
  ACCEPTED_VIEWS,
  FORBIDDEN_COLUMN_PATTERNS,
  GLOBAL_TABLES,
  INFRASTRUCTURE_TABLES,
} from "./expected-schema.js";
import {
  findForeignKeysMissingTownScope,
  readSchemaSnapshot,
  type SchemaSnapshot,
} from "./introspection.js";

const SNAPSHOT_PATH = new URL("../schema-snapshot.json", import.meta.url);

describe.skipIf(!shouldRunDatabaseTests())("the migrated schema", () => {
  let handle: DisposableDatabase | undefined;
  let snapshot: SchemaSnapshot;

  beforeAll(async () => {
    handle = await createDisposableDatabase();
    snapshot = await readSchemaSnapshot(handle.pool);
  }, 180_000);

  afterAll(async () => {
    await handle?.dispose();
  });

  it("contains exactly the forty accepted tables plus the migration ledger", () => {
    expect(Object.keys(snapshot.tables).toSorted()).toStrictEqual(
      [...ACCEPTED_TABLES, ...INFRASTRUCTURE_TABLES].toSorted(),
    );
    expect(ACCEPTED_TABLES).toHaveLength(40);
  });

  it("matches the committed snapshot exactly in both directions", async () => {
    // The snapshot is regenerated by `pnpm db:snapshot` and reviewed as a diff.
    // A test that could rewrite its own expectation would prove nothing.
    const committed = JSON.parse(
      await readFile(SNAPSHOT_PATH, "utf8"),
    ) as SchemaSnapshot;
    expect(snapshot).toStrictEqual(committed);
  });

  it("scopes every foreign key between town-owned rows by town", () => {
    expect(findForeignKeysMissingTownScope(snapshot, GLOBAL_TABLES)).toStrictEqual([]);
  });

  it("gives every town-owned table a key that begins with town_id", () => {
    const offenders: string[] = [];
    for (const table of ACCEPTED_TABLES) {
      if (GLOBAL_TABLES.includes(table as (typeof GLOBAL_TABLES)[number])) continue;
      const primaryKey = Object.values(snapshot.tables[table]?.constraints ?? {}).find(
        (definition) => definition.startsWith("PRIMARY KEY"),
      );
      if (primaryKey === undefined) {
        offenders.push(`${table} (no primary key)`);
      } else if (
        !primaryKey.startsWith("PRIMARY KEY (town_id") &&
        !(table === "towns" && primaryKey.startsWith("PRIMARY KEY (id"))
      ) {
        offenders.push(`${table} (${primaryKey})`);
      }
    }
    expect(offenders).toStrictEqual([]);
  });

  it("stores no column that could hold a credential or a raw address", () => {
    const offenders: string[] = [];
    for (const [tableName, table] of Object.entries(snapshot.tables)) {
      for (const column of Object.keys(table.columns)) {
        if (FORBIDDEN_COLUMN_PATTERNS.some((pattern) => pattern.test(column))) {
          offenders.push(`${tableName}.${column}`);
        }
      }
    }
    expect(offenders).toStrictEqual([]);
  });

  it("indexes episode recall by town and NPC before the vector", () => {
    const definition = snapshot.tables["episodes"]?.indexes["ix_episodes__embedding"];
    expect(definition).toBeDefined();
    expect(definition).toContain("(town_id, npc_id, embedding");
    // Decision 005 permits omitting the predicate where a version cannot
    // express it; v25.4 can, so the index is expected to carry it.
    expect(definition).toContain("WHERE (embedding_status = 'ready'");
  });

  it("keeps every token, secret, and hash column as BYTES rather than text", () => {
    const offenders: string[] = [];
    for (const [tableName, table] of Object.entries(snapshot.tables)) {
      for (const [column, details] of Object.entries(table.columns)) {
        if (!/_hash$|^token_hash$/.test(column)) continue;
        if (details.type !== "bytea") offenders.push(`${tableName}.${column}`);
      }
    }
    expect(offenders).toStrictEqual([]);
  });

  it("stores model cost as an exact decimal, never floating point", () => {
    for (const table of ["agent_runs", "model_cost_reservations"] as const) {
      for (const [column, details] of Object.entries(
        snapshot.tables[table]?.columns ?? {},
      )) {
        if (!/cost$/.test(column)) continue;
        expect(details.type, `${table}.${column}`).toBe("numeric");
      }
    }
  });

  it("declares the thirteen accepted inspection views", () => {
    expect(ACCEPTED_VIEWS).toHaveLength(13);
    expect(snapshot.views.toSorted()).toStrictEqual([...ACCEPTED_VIEWS].toSorted());
  });

  it("stores every timestamp with a time zone", () => {
    const offenders: string[] = [];
    for (const [tableName, table] of Object.entries(snapshot.tables)) {
      for (const [column, details] of Object.entries(table.columns)) {
        if (!/_at$/.test(column)) continue;
        if (details.type !== "timestamp with time zone") {
          offenders.push(`${tableName}.${column} (${details.type})`);
        }
      }
    }
    expect(offenders).toStrictEqual([]);
  });
});
